---
title: "PDF preparation"
format: html
---



```{r}
library(googledrive)
library(tidyverse)
library(glue)
source("https://raw.githubusercontent.com/forrtproject/FReD-data/refs/heads/main/clean_cos_fred.R")


ds_fully_raw <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR_62H8liC0P3-WQ1xx4UalDnvqzPfObWBFwQAgVH6JhF3dPBFXd7AgFK_OljxFWQkNtUYdnUbuFTpe/pub?output=csv", skip = 1)

cleaned <- clean_fred_data(ds_fully_raw)

ds_raw <- cleaned$cleaned_data

# filter for validated - chosen entries
# changed this as base-R subsetting struggles with NAs
ds <- ds_raw %>% filter(status == "validated - chosen")

canon <- function(x) tolower(trimws(x))
expected_keys <- unique(canon(c(ds$file_o, ds$file_r)))

drive_auth() 

source_folder <- "1VMbkD0_rORNE9MH_0aO_yywfZ-y5_ir1"
dest_folder <- "10GSKukVmMe9SmzcDvATxTjm_VqMyDqc5"

src_files  <- drive_ls(as_id(source_folder)) %>% mutate(key = canon(name))
dest_files <- drive_ls(as_id(dest_folder))   %>% mutate(key = canon(name))

relevant_src <- src_files %>%
  semi_join(tibble(key = expected_keys), by = "key") %>%
  distinct(key, .keep_all = TRUE) 

unexpected <- dest_files %>%
  filter(!(key %in% expected_keys))

if (nrow(unexpected) > 0) {
  walk(unexpected$id, drive_rm)
}

# refresh dest_files after deletion
dest_files <- drive_ls(dest_id) %>% mutate(key = canon(name))

# compute which relevant files are missing
to_copy <- relevant_src %>%
  anti_join(dest_files, by = "key")

to_copy <- to_copy[2:nrow(to_copy), ]  # skip first row due to automated malware concern

# copy missing files
copied <- map2(
  to_copy$id,
  to_copy$name, 
  ~ drive_cp(as_id(.x), path = dest_id, name = .y),
  .progress = TRUE
)

dest_files <- drive_ls(dest_id) %>% mutate(key = canon(name))
missing_expected <- setdiff(expected_keys, dest_files$key)
missing_expected
```


```{r}
intersect(list.files("/Users/lukaswallrich/Downloads"), files_missing)

file.copy(from = file.path("/Users/lukaswallrich/Downloads/pdf_downloads/", intersect(list.files("/Users/lukaswallrich/Downloads/pdf_downloads/"), files_missing)),
          to = file.path("/Users/lukaswallrich/Downloads/pdf_downloads/upload",
                         intersect(list.files("/Users/lukaswallrich/Downloads/pdf_downloads/"), files_missing)))

file.rename(list.files("/Users/lukaswallrich/Downloads/pdf_downloads", full.names = TRUE),
            file.path("/Users/lukaswallrich/Downloads/pdf_downloads",
                      tolower(basename(list.files("/Users/lukaswallrich/Downloads/pdf_downloads")))))

replace_na_filename <- function(filename) {
  filename %>% 
    na_if(".pdf") %>% 
    na_if("na.pdf") %>% 
    na_if("NA - USE URL")
}

files_missing <- replace_na_filename(files_missing) %>% unique()

files_missing <- setdiff(files_missing, list.files("/Users/lukaswallrich/Downloads/pdf_downloads/found"))

# Move the relevant files into a "found" subdirectory
files_moved <- file.rename(from = file.path("/Users/lukaswallrich/Downloads/pdf_downloads", intersect(list.files("/Users/lukaswallrich/Downloads/pdf_downloads"), files_missing)),
                            to = file.path("/Users/lukaswallrich/Downloads/pdf_downloads/found",
                                           intersect(list.files("/Users/lukaswallrich/Downloads/pdf_downloads"), files_missing)))


probs <- ds %>% select(file = file_o, doi = doi_o) %>% 
  bind_rows(ds %>% select(file = file_r, doi = doi_r)) %>%
  distinct() %>%
  filter(file %in% files_missing)

probs %>% 
  pull(doi) %>% 
  str_subset("^10\\.") %>% clipr::write_clip()


```

You can add options to executable code like this 

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
