name: Run FReD ETL

on:
  workflow_dispatch:
    inputs:
      target_tables:
        description: "Which database to load data into"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - original

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ETL dependencies
        working-directory: fred_dynamodb_loader
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Select target tables
        run: |
          if [ "${{ inputs.target_tables }}" = "original" ]; then
            echo "Using ORIGINAL tables"
            echo "PREFIX_TABLE=${{ secrets.PROD_PREFIX_TABLE }}" >> $GITHUB_ENV
            echo "DOI_TABLE=${{ secrets.PROD_DOI_TABLE }}" >> $GITHUB_ENV
            echo "CLEAR_TABLES=0" >> $GITHUB_ENV
          else
            echo "Using TEST tables"
            echo "PREFIX_TABLE=${{ secrets.TEST_PREFIX_TABLE }}" >> $GITHUB_ENV
            echo "DOI_TABLE=${{ secrets.TEST_DOI_TABLE }}" >> $GITHUB_ENV
            echo "CLEAR_TABLES=1" >> $GITHUB_ENV
          fi

      - name: Confirm selected tables
        run: |
          echo "PREFIX_TABLE = $PREFIX_TABLE"
          echo "DOI_TABLE = $DOI_TABLE"
          echo "CLEAR_TABLES = $CLEAR_TABLES"

      - name: Debug files
        run: |
          pwd
          ls -R

      - name: Run ETL
        run: |
          python load_fred_to_dynamodb.py ../output/flora.csv